### ISSUE TITLE
Which sublimation enthalpy difference should throw a warning?

### ISSUE THREAD

**Issue by bizzinho** [bizzinho/ADDICT_Issues#19]

**Comment by carltilbury** [comment]
A reasonable estimate would be Elatt to be within 0 and 3 kcal/mol larger than dHsub (up to 5 RT difference at 300 K).  I think it's not worth considering the temperature at which dHsub is measured; though that's the actual T to use.  Within that region they're effectively identical since we don't know what the relationship should be as it depends on the specific degrees of freedom for the molecule.  

The other way would be up to 10% larger is OK.

Maybe put in both conditions and only if both are not satisfied produce the warning.

If we wanted a major warning in addition we might choose if Elatt were more than 10% smaller or 20% larger than dHsub.

**Comment by bizzinho** [comment]
Okidoki, will do

**Comment by bizzinho** [comment]
Done, following logic is applied:

absDiff < 3 || (relDiff<=0.1 && relDiff >= -0.1)

--> everything if fine

relDiff >= -0.1 && relDiff <= 0.2

--> reasonable

else:

--> bad!
