### ISSUE TITLE
paracetamol shape in vapor

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#24]
(1) The vapor shape of paracatamol only has two different facets {110} and {001}, but there are 6 different facets shown in the bottom of crystal shape. It will be better to set the program only show the currently displayed facets below the crystal shape. 
(2) Could you let me know what the ln(L{-2 0 1}/L{1 1 1}) mean in the vertical axis of morphology map for paracetamol vapor growth, since there is no {-2 0 1} facet for paracetamol vapor shape. 
(3) If I input a value (such as -18) at the Sub. Heat [kcal/mol] of "Advanced Setup" section, can you put "Experimental lattice energy=-28kcal/mol" below the S=1.04 line in top right figure?

![5](https://cloud.githubusercontent.com/assets/17035064/13479737/f3068c60-e08d-11e5-8de7-18077568e884.jpg)

**Comment by carltilbury** [comment]
Regarding 1 - I think we should leave the other facets in, even if they're grown out in the shape prediction.  It's useful to have them when you move around the morphology map - that's also why there is the ordinate axis with face -201

**Comment by bizzinho** [comment]
Hey guys,

1. I could change the legend entries below the crystal, but I would strongly advise against it. Not only would it slow down the feedback because of the additional (and not so trivial) check which facet is present, it would also result in some ugly flipflopping of the legend entries width or color (if I decide to grey them out instead), etc. 

2. Yeah I'm not sure I understand the question... even though the facet is absent, ADDICT has calculate a relative growth rate for it, the y-coordinate in this case corresponds to that value. The absolute value is significant because it tells you by how much you would have to slow down facet -201 to make it appear on the crystal surface.

3. I find the display already overcrowded tbh. For the sake of simplicity I would recommend not doing this, but if you want it I will do it of course.

**Comment by carltilbury** [comment]
I agree with Dave I think no changes need to be implemented for these.
