### ISSUE TITLE
The horizontal axis of lattice energy figure

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#25]
The horizontal axis of lattice energy figure is not shown correctly.
![4](https://cloud.githubusercontent.com/assets/17035064/13479809/6db96b3a-e08e-11e5-92d5-ee681c74664f.jpg)

**Comment by Jinjin-Li** [comment]
should be changed to Radius [A]

**Comment by bizzinho** [comment]
Now this is interesting, because it appears correctly for me also in Matlab 2013b.

Can you do me a favor and type in 

```
char(197)
```

into your Matlab command window and tell me what you see? If you don't see the Angstrom symbol I would assume the error has to do with the charset that is installed on your PC (possibly due to your Chinese installation?)

**Comment by Jinjin-Li** [comment]
Dave, I can see the Angstrom symbol in my Matlab, but the Angstrom symbol doesn't show on ADDICT. 
Carl, can you check this in your computer? Thanks







From: Dave Ochsenbein
Date: 2016-03-04 00:03
To: bizzinho/ADDICT_Issues
CC: Jinjin-Li
Subject: Re: [ADDICT_Issues] The horizontal axis of lattice energy figure (#25)
Now this is interesting, because it appears correctly for me also in Matlab 2013b.
Can you do me a favor and type in 
char(197)

into your Matlab command window and tell me what you see? If you don't see the Angstrom symbol I would assume the error has to do with the charset that is installed on your PC (possibly due to your Chinese installation?)

**Comment by bizzinho** [comment]
aiaiai... 

ok, can you try the following:

```
figure
xlabel(char(197),'fontsize',14)
saveas(gcf,'test','fig')
```

This will create a matlab figure file in your current folder... please let me know whether this figure file looks fine or not...

**Comment by Jinjin-Li** [comment]
Hello Dave，
This figure looks good. It's weird.
![1](https://cloud.githubusercontent.com/assets/17035064/13587394/d02795c0-e47c-11e5-8c07-bfd0e2269967.png)

**Comment by bizzinho** [comment]
And the other plot still looks wrong?? AFAIK the difference between the two codes is marginal...

**Comment by Jinjin-Li** [comment]
Hello Dave,

The Angstrom symbol and other plot still looks wrong in Matlab 2013, even I changed another computer to test. 
I convinced Mike that we will use Matlab 2014 instead of Matlab 2013. I just installed Matlab 2014a in my computer. Could you please send us a new ADDICT version with Matlab 2014. I hope that all the questions will be solved this time.

Thanks
Jinjin

**Comment by bizzinho** [comment]
Hey Jinjin,

The code for Matlab 2014 is identical to the one for 2013 ;) but I will send you the last version in the next few days

I think there is no need to convince the users to switch to Matlab 2013, I still believe that this might be a specific problem with your character set installation... do you know anyone else with Matlab 2013 in your lab? Maybe he/she could try it out. I'll do the same here!

**Comment by bizzinho** [comment]
about to be tested on another computer running Matlab 2013b

**Comment by bizzinho** [comment]
Indeed, the figure looks fine also on another computer... I'm positive now that the problem lies in some issue with the character set installed on your computer, @Jinjin-Li 

Unfortunately, since I don't know your exact installation this is very difficult to debug. Nonetheless, given that the majority of users will run on an English installation, I think we can safely recommend ADDICT for use also on Matlab 2013b...
