### ISSUE TITLE
Error using PBC viewer

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#26]
I couldn't get the PBC viewer to run for paracetamol.  Just ran it for water and tried to start up the viewer.

![capture1](https://cloud.githubusercontent.com/assets/16385845/13515773/23888f74-e169-11e5-8e21-76de53511663.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16385845/13515772/238889b6-e169-11e5-8240-f767396d7147.PNG)

**Comment by bizzinho** [comment]
I start to suspect something's fishy with your paracetamol file. I sent you my current addict files and the cif file for pam I received from Jinjin, please try it and let me know whether the PBC viewer (works for me in 2014b) as well as the solvent sweep work then!

**Comment by carltilbury** [comment]
Good news is that the new files fix both the PBC viewer error and the solvent sweep warning.  Bad news is I don't understand why HXACAN19 (the cif & mol2 files I was using) was having problems - HXACAN01 looks identical in structure to me.  Seeing as building in more robustness for different cif files is a whole new beast I guess close these issues.

**Comment by bizzinho** [comment]
Yeah the problem here is that I have not modified the cif file reader in any way afaik and - tbh - I wouldn't know how to because it's a mess ;)

We might look at it at a later point in time maybe after the release? It's probably something minor, hidden away in the swamp land that is read_cif.m ...

I close it.
