### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#3]
Right now the temperature and supersaturation at which the shape is predicted are not reported on the output screen, only the solvent.  While these are input variables that probably have a small effect, it might be worth adding them in case new mechanisms ever make their way into ADDICT.

Also, I don't see the slider working for naphthalene:

![error3](https://cloud.githubusercontent.com/assets/16385845/12710196/ff02bea4-c868-11e5-8642-c93eff95a5a7.PNG)

**Comment by bizzinho** [comment]
Regarding S and T, I agree. Any idea where to place the info? I feel like the title might get too long for some instances if we append that information...

I fixed the slider issue for the next patch, the problem was a missing enable on. If you want, you can fix it yourself by adding the following line after line 1359 in ADDICT (within the Mred if check):

> set(O.gui.hslider,'enable','on');

**Comment by carltilbury** [comment]
How about putting another title within the pane of the shape prediction?  E.g.

NAPHTA10 in Vapor (bold)
T=298 K
S=1.04
L = [1 1.77 2.22 2.36]

The S and T probably don't need to be reported on each tab, just the overall shape.  And the current title that persists as you change tabs can stay, reinforcing that ADDICT is mainly useful in selecting the solvent.

Another suggestion would be to move the L data to alongside the colour key for the faces - that way it makes it slightly more obvious which number represents which face.

**Comment by bizzinho** [comment]
OK, I'll give it a try!

**Comment by bizzinho** [comment]
Has been done
