### ISSUE TITLE
Lovastatin solvent sweep

### ISSUE THREAD

**Issue by Jinjin-Li** [bizzinho/ADDICT_Issues#31]
![3](https://cloud.githubusercontent.com/assets/17035064/13901613/f2b10da6-ede6-11e5-9046-d46bddf809a5.jpg)
Hello Dave,
The above figure is the solvent sweep of Lovastatin.
(1) Can you remove/skip these warnings?
(2) For the solvent sweep of lovastatin, there are only three points in the morphology map. The middle point at lg(L200/L210)=lg(L101/L210)=0 corresponds to the water, which means at this point L(200)=L(210)=L(101). But the shape of lovastatin in water is a very thin plate. Is this reasonable?

Mike said we should release ADDICT version 2.0 on March 24, 2016. Please let me know if you need any information from us. Thank you.

**Comment by bizzinho** [comment]
Dear Jinjin,

I was outside of Switzerland and therefore couldn't work much on this, but I can fix these warnings. Regarding the image, I can see that one of the facets has a very small aspect ratio (number five -> 020) which would explain the platelet like shape. I can have a look at the sweep in more detail.

In general, if morphologies live in completely different spaces from each other, they will not be shown in the same morphology map... so it is possible to have less than 32 points in one map.

March 24th US time seems doable to me.

**Comment by bizzinho** [comment]
Would it be possible to talk in Skype tomorrow 5pm CET?

**Comment by Jinjin-Li** [comment]
OK, let's talk in Skype tomorrow at 5pm CET.

**Comment by bizzinho** [comment]
As suggested, the reason is that many of these points overlap, i.e., they have a relative growth rate for two facet families equal to 50 or higher. At least that's what it looks like when I calculate the sweep. I will check this in slightly more detail tomorrow, but I'm pretty confident that's the cause.

PS. earlier, we had a Rmax = 100, this might have affected the looks of things. also, some of the points in the bottom are only close to each other, not exactly on top. in the old version where we had a natural logarithm and a limit of +/- 3 these points might have looked farther apart.

**Comment by bizzinho** [comment]
Warnings have been removed and there is a reasonable explanation for the points.
